# Generated by Django 4.2.1 on 2023-06-12 05:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_alter_product_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField(null=True)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('payment_method', models.CharField(choices=[('Cash on Delivery', 'Cash on delivery'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti')], max_length=100)),
                ('payment_status', models.BooleanField(default=False, null=True)),
                ('phone_no', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(20)])),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
